  server:
    port: 8088

  spring:
    datasource:
      url: jdbc:h2:mem:walletdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: org.h2.Driver
      username: sa
      password: password

    jpa:
      hibernate:
        ddl-auto: update
      open-in-view: false   # ✅ Prevents Hibernate warning
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    h2:
      console:
        enabled: true
        path: /h2-console

    thymeleaf:
      check-template-location: false

  logging:
    level:
      root: INFO
      io.netty: ERROR

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
